/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailGeneratorRouteImport } from './routes/email-generator'
import { Route as MeetingSummariserRouteImport } from './routes/meeting-summariser'
import { Route as ResearchAssistantRouteImport } from './routes/research-assistant'
import { Route as SavedWorkRouteImport } from './routes/saved-work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailGeneratorRoute = EmailGeneratorRouteImport.update({
  id: '/email-generator',
  path: '/email-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingSummariserRoute = MeetingSummariserRouteImport.update({
  id: '/meeting-summariser',
  path: '/meeting-summariser',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAssistantRoute = ResearchAssistantRouteImport.update({
  id: '/research-assistant',
  path: '/research-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedWorkRoute = SavedWorkRouteImport.update({
  id: '/saved-work',
  path: '/saved-work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summariser': typeof MeetingSummariserRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/saved-work': typeof SavedWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summariser': typeof MeetingSummariserRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/saved-work': typeof SavedWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summariser': typeof MeetingSummariserRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/saved-work': typeof SavedWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-generator'
    | '/meeting-summariser'
    | '/research-assistant'
    | '/saved-work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-generator'
    | '/meeting-summariser'
    | '/research-assistant'
    | '/saved-work'
  id:
    | '__root__'
    | '/'
    | '/email-generator'
    | '/meeting-summariser'
    | '/research-assistant'
    | '/saved-work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailGeneratorRoute: typeof EmailGeneratorRoute
  MeetingSummariserRoute: typeof MeetingSummariserRoute
  ResearchAssistantRoute: typeof ResearchAssistantRoute
  SavedWorkRoute: typeof SavedWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-generator': {
      id: '/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof EmailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-summariser': {
      id: '/meeting-summariser'
      path: '/meeting-summariser'
      fullPath: '/meeting-summariser'
      preLoaderRoute: typeof MeetingSummariserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-assistant': {
      id: '/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof ResearchAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-work': {
      id: '/saved-work'
      path: '/saved-work'
      fullPath: '/saved-work'
      preLoaderRoute: typeof SavedWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailGeneratorRoute: EmailGeneratorRoute,
  MeetingSummariserRoute: MeetingSummariserRoute,
  ResearchAssistantRoute: ResearchAssistantRoute,
  SavedWorkRoute: SavedWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
